version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  selenoid-ui:
    network_mode: bridge
    container_name: selenoid_ui
    image: aerokube/selenoid-ui
    ports:
     - 8080:8080
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    network_mode: bridge
    container_name: selenium_autotests
    build: .
    links:
     - selenoid
    depends_on:
     - selenoid
    command: ["pytest"]
